version: "3"
services:
  web:
    build: .
    command: bin/rails server -p 3000
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres@db
  db:
    image: postgres:14
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: msrd_development
  redis:
    image: redis:6.0